# Generated by Django 5.1.1 on 2024-09-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_medicationname_alter_medication_medication_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicationname',
            options={'ordering': ['medication_name']},
        ),
    ]
