# Generated by Django 5.1.1 on 2024-09-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_medicationname_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['chosen_medication']},
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='medication_name',
            new_name='chosen_medication',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='amount_of_medication',
        ),
        migrations.AddField(
            model_name='medication',
            name='medication_dose',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
