# Generated by Django 5.1.1 on 2024-09-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_prescription_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='user',
        ),
    ]
